public class Tariff {
    String id;
    String name;
    int minutes;
    boolean unlimitedMinutes;
    int gigabytes;
    int sms;
    boolean unlimitedVk;
    boolean unlimitedOk;
    boolean unlimitedFacebook;
    boolean unlimitedInstagram;
    boolean unlimitedWhatsApp;
    boolean unlimitedViber;
    boolean unlimitedTamTam;
    boolean unlimitedYouTube;
    boolean unlimitedYandexMaps;
    boolean unlimitedYandexNavigator;
    boolean unlimitedTwitch;
    boolean unlimitedDiscord;
    boolean unlimitedTinder;
    boolean unlimitedBadoo;
    boolean unlimitedAmediateka;
    int price;
    boolean bestseller;
    String imageVkUrl;
    String imageOkUrl;
    String imageInstUrl;
    String imageFacebookUrl;
}
